### ISSUE TITLE
Building and running application on Windows

### ISSUE THREAD

**Issue by romansp** [rolandgeider/wger#197]
Tried running application on Windows (as I use Windows as development environment). Everything went surprisingly smooth, though stumbled upon few issues related to wger source code:

1. `media_folder_path` needs `\` escaping
2. Install `bower` globally with `-g` switch, so we don't need `BOWER_PATH` to be defined. It points to wrong file on Windows. Or need to somehow add `.cmd` extension while trying to restore packages on Windows.

I will create PR that fixes those.

Also stumbled upon few issues regarding python and django setup on windows. Can add complete **Run on Windows** guide if needed.

**Comment by rolandgeider** [comment]
Thanks for finding those, it's good to hear that the application (almost) runs in windows! Did you do something *very* different to install it? If you could add those steps to the documentation, it would be great.

About number 2, I'm not sure about installing bower globally. If you e.g. want to run the application on a shared host (e.g. the way wger.de is running), you won't be able to do it. Since the settings file is a regular python file I think we could just check that [the platform](https://docs.python.org/2/library/sys.html#sys.platform) is windows. Something like this:

```python
if sys.platform.startswith('windows'):
    BOWER_PATH = os.path.join(BASE_DIR, 'node_modules', '.bin', 'bower.cmd')
else:
    BOWER_PATH = os.path.join(BASE_DIR, 'node_modules', '.bin', 'bower')
```

**Comment by romansp** [comment]
Thanks for the snippet! Will try this out and rebase commits in PR. 

Not much was *different* on Windows. 

First I misused 32 and 64-bit installers and packages. But main issue was that packages failed to build from source, so I had to download precompiled binaries and install them separately via `wheel` (I guess?). Those were: `pillow` and `reportlab`. 

Don't know if something can be done on wger side to fix this.

**Comment by rolandgeider** [comment]
Ah yes, pillow and reportlab, can't say I'm surprised. While they usually can be installed just fine, they are sometimes problematic, since you have to have additional development packages just so they compile. I guess the only thing we can do on our side is just to mention it somewhere.

**Comment by romansp** [comment]
Updated PR, ready to be merged.

**Comment by rolandgeider** [comment]
Ready, steady, done!
