### ISSUE TITLE
See list of all user accounts, with admin functions

### ISSUE THREAD

**Issue by umuzidan** [rolandgeider/wger#212]
Feature: As a General Manager (admin user), I want to see a list of all registered user accounts on the site and include normal admin functions, such as reset password, update details, disable, delete, and ban.

**Comment by rolandgeider** [comment]
This is already possible but only for the members of a gym. It shouldn't be too difficult to generalize the templates and the views to allow for this case.

**Comment by umuzidan** [comment]
Possible solution:
1 .User clicks on their username menu located on the far right of the tool bar
2. User clicks on "Users" - a new option on the drop down menu under the Administration section
3. User is directed to a new page which displays all users in list form

**Comment by rolandgeider** [comment]
Yes, the administration sections seems the right place to put the new option

**Comment by rolandgeider** [comment]
This is implemented in the gym-refactor branch. General managers can access the list of all users present in the system. Clicking on a user opens the regular detail page where it's possible to edit, delete and (de)activate them. Not closing the issue yet because there's probably some polishing to do.
![bildschirmfoto vom 2015-10-29 21 09 01](https://cloud.githubusercontent.com/assets/2280729/10830892/7ce79e2e-7e82-11e5-9d9c-1e9faa0ad2f3.png)

**Comment by rolandgeider** [comment]
Branch was merged into master, closing this issue.

@umuzidan feel free to start implementing your things (you'll need to do a ``python manage.py migrate`` to sync up the database)
