### ISSUE TITLE
Specify different weight options while adding exercises to a workout

### ISSUE THREAD

**Issue by umuzidan** [rolandgeider/wger#217]
As a User, I want the ability to specify different repetition options while adding exercises to a workout
Weight Options:
1) Pounds
2) Kilos
3) Body Weight
4) Miles Per Hour
5) Kilometers Per Hour
6) Miles
7) Kilometers

Note: Regarding weight option #2, kilos, I am aware the system has the ability to switch between imperial and metric, however this option should persist because the user's equipment may only be in pounds or kilos. Giving the user the ability to specify a particular exercise in kilos while their profile is in pounds is very helpful.

**Comment by rolandgeider** [comment]
Merged in master, together with #216

**Comment by robotoART** [comment]
As a fitness trainer and jr web developer, I think this project rocks! 
Hate to bring this one back from the grave, so apologies ahead of time.

Under weight add, https://wger.de/en/weight/add/ , and Daily calories calculator, https://wger.de/en/nutrition/calculator/calories/. 
Is there any way I can help to add this new units option functionality to the live example on the website https://wger.de/ ?
Or is it there but I just don't see it?

It helps when demonstrating the app quickly online without having to register or login because quite a few seem to ask if they can just use it online instead of installing the Android app.

I'm new to this project, but I plan on contributing more often.
Just cloned the repo and will start playing with the code once I finish my some school projects.
Thanks.
