### ISSUE TITLE
Can't delete weight entries.

### ISSUE THREAD

**Issue by purplebird** [rolandgeider/wger#234]
You can edit existing ones, but there is no way to remove a weight entry (accidental entry, etc).

**Comment by purplebird** [comment]
I looked at implementing this but couldn't figure out how the dialog box actually worked (not knowing js didn't help).

**Comment by rolandgeider** [comment]
There is already a ticket for this, #129, the problem I have is that I'm not sure how to present the option to the users and I don't want to use the dialog for this (should be used only to add and edit entries). On the other hand, since a weight entry has only a date and a weight, if there's an accidental entry, it can be *recycled* later on. But that's an ugly workaround, I know.

**Comment by rolandgeider** [comment]
Closing here
