### ISSUE TITLE
Commas are overused

### ISSUE THREAD

**Issue by ywecur** [rolandgeider/wger#265]
I've noticed while translating that commas are overused in the vast majority of cases. I've also found several typos I'd like to correct.

Sorry if this sounds rude, but I believe this should be corrected.

I could not correct these while translating, but would like to. How would I go about doing this?

**Comment by rolandgeider** [comment]
Don't worry, it's not rude, the many commas come, probably, from my German side.

It is not possible to edit the source strings in transifex, you'd either need to checkout the source code for wger, fix them there and send a pull request or just keep adding issues in transifex. On the other hand, since issues in transifex are a bit hidden, perhaps you can just collect what you found and send me a PM there, whatever is easiest for you.

**Comment by rolandgeider** [comment]
Closing here, feel free to reopen
